### ISSUE TITLE
アイコン画像の変更

### ISSUE THREAD

**Issue by Rintan** [GenbuProject/Google-Plus-UI-for-Mastodon#3]
[Wiki](https://github.com/stylish-userstyles/stylish/wiki/Replacing-images-in-img-tags) を参考に、ホームなどのアイコンをGoogle+のものに置き換える。

**Comment by GenbuHase** [comment]
良ければ手伝いましょうか…？？

**Comment by Rintan** [comment]
ありがとうございます！
Issueには個人的な修正予定などを書き込んでいくつもりです。(Google Keepでやるのが面倒になってきたので)

**Comment by GenbuHase** [comment]
@Rintan 把握です(^^ゞ

**Comment by GenbuHase** [comment]
一応出来ました…
